### ISSUE TITLE
Default event template doesn't render

### ISSUE THREAD

**Issue by davidgorges** [manuxi/SuluEventBundle#4]
the default template uses the twig filter `format_datetime`. Since this filter is not part of the default twig package it requires two additional packages to be installed:

```
composer require twig/intl-extra
composer require twig/extra-bundle
```
Could be useful to add these as dependencies or mention in setup maybe?

**Comment by manuxi** [comment]
Thank you for that hint, I'll add it later

**Comment by manuxi** [comment]
Done
